//
// Generated file, do not edit! Created by nedtool 5.5 from mytictoc.msg.
//

#ifndef __MYTICTOC_M_H
#define __MYTICTOC_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



class MyTictocMsg;
/**
 * Class generated from <tt>mytictoc.msg:2</tt> by nedtool.
 * <pre>
 * message MyTictocMsg
 * {
 *     int source;
 *     int destination;
 *     char msg = 'M';
 *     int hopCount = 0;
 * }
 * </pre>
 */
class MyTictocMsg : public ::omnetpp::cMessage
{
  protected:
    int source = 0;
    int destination = 0;
    char msg = 'M';
    int hopCount = 0;

  private:
    void copy(const MyTictocMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MyTictocMsg&);

  public:
    MyTictocMsg(const char *name=nullptr, short kind=0);
    MyTictocMsg(const MyTictocMsg& other);
    virtual ~MyTictocMsg();
    MyTictocMsg& operator=(const MyTictocMsg& other);
    virtual MyTictocMsg *dup() const override {return new MyTictocMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSource() const;
    virtual void setSource(int source);
    virtual int getDestination() const;
    virtual void setDestination(int destination);
    virtual char getMsg() const;
    virtual void setMsg(char msg);
    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MyTictocMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MyTictocMsg& obj) {obj.parsimUnpack(b);}

#endif // ifndef __MYTICTOC_M_H

